# Spring properties
spring:
#  application:
#     name: order-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    enabled: false
  enums:
    mongodb:
      host: mongo
      port: 27017
      database: test_db
      username: test_user
      password: pa55w0rd

#Admin user
admin:
  token: xlmJlgXY7token3jkrPxbAsp0CR
  restaurant: 99999

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8089   # HTTP (Tomcat) port


#ORDER PROPERTIES
order:
  rememberMinutesBefore: 10
  time:
    margin:
      min: 30
      max: 60
  tablefor:
    max: 5
  timetoeat: 30
  minimumvalue: 10.00
  split:
    invitations:
      max: 10
  payment:
    sync:
      bulkSize: 50

service: #RESTAURANT-SERVICE
  user: #USER-SERVICE
    host: user
    port: 8085
  payment:
    host: payment
    port: 8086
  searching: #SEARCHING SERVICE
    host: search
    port: 8087
  restaurant:
    host: restaurant
    port: 8088
  notification: #NOTIFICATION-SERVICE
    host: notification
    port: 8090
    staticToken: poIURGHRIPokrogpkrg4894-hrtht*

endpoints:
    health:
        sensitive: false