# Spring properties
spring:
  application:
     name: order-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    enabled: false
  enums:
    mongodb:
      host: 10.132.0.6
      port: 27017
      database: test_db
      username: test_user
      password: pa55w0rd

#Admin user
admin:
  token: xlmJlgXY7token3jkrPxbAsp0CR
  restaurant: 99999

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 80   # HTTP (Tomcat) port


#ORDER PROPERTIES
order:
  rememberMinutesBefore: 20
  time:
    margin:
      min: 30
      max: 60
  tablefor:
    max: 5
  timetoeat: 30
  minimumvalue: 10.00
  split:
    invitations:
      max: 10
  payment:
    sync:
      bulkSize: 50


service: #RESTAURANT-SERVICE
  restaurant:
    host: restaurant-service
    port: 80
  user: #USER-SERVICE
    host: user-service
    port: 80
  notification: #NOTIFICATION-SERVICE
    host: notification-service
    port: 80
    staticToken: poIURGHRIPokrogpkrg4894-hrtht*
  searching: #SEARCHING SERVICE
    host: searching-engine-service
    port: 80
  payment:
    host: payment-service
    port: 80

endpoints:
    health:
        sensitive: false